### PR TITLE
Update 1

### PR DESCRIPTION
**Pull request by Loggan08**
Inverted if, removed unreachable code

### CODE REVIEW

**Comment by Loggan08** [comment]
Also I suggest bumping up to .Net 4.5.2

**Comment by Loggan08** [comment]
Why is this pointless? explain

**Comment by ChewyMoon** [comment]
Because resharper abuse on the loader is point less.

**Comment by Loggan08** [comment]
Well, do you see any harm done in accepting this pull?

**Comment by imsosharp** [comment]
+1 resharper sucks

**Pull request closed without merging**
