### PR TITLE
Update Repositories.txt

### PR DESCRIPTION
**Pull request by blacky**
blackyy => blacky

### CODE REVIEW

**Comment by ChewyMoon** [comment]
3 yrs later

**Comment by blacky** [comment]
So rude Chewy. Also updated WorstPing => L33T and removed Hellsing. PJSalt.

**Comment by Hellsing** [comment]
Cuz I deserve to be removed? :^ )

**Comment by blacky** [comment]
Someone suggested it. :^)

**Comment by ChewyMoon** [comment]
IT WAS DANIEL #LEAK4JESUS

**Comment by Hellsing** [comment]
Everywhere 2 faced people Kappa
But good to know who's your friend and who's not :P

**Comment by ChewyMoon** [comment]
:chewy:

**Comment by legacy3** [comment]
please refuse from open useless commits

**Pull request closed without merging**
