### PR TITLE
Update Portuguese.xaml

### PR DESCRIPTION
**Pull request by madk**

### CODE REVIEW

**Comment by Crisdmc** [comment]
Always wonder if this is PT-PT or PT-BR?

**Comment by madk** [comment]
What i changed i believe are spelled the same way in Brazil, but that he whole file it's kinda mixed.

**Comment by andreluis034** [comment]
@Crisdmc It's supposed to be PT-PT.

**Comment by Crisdmc** [comment]
I am Brazilian we understand, just a few words attracted my attention, by weird, common and wrong, and also how it is written ^^.
Like:

Actualizar -> Atualizar
Activar -> Ativar
Desactualizado -> Desatualizado
Ficheiro -> Arquivo
Seguinte -> Próximo, Avançar
Descarga -> Download
Eliminar -> Excluir, "Deletar"
Partilhar -> Compartilhar
Procurar -> Pesquisar, Buscar 
Consola -> Console
Estado -> "Status"

Regista-te
Por favor reinicia o LeagueSharp
Tens a certeza que desejas eliminar os assemblies selecionados?
A descarregar os dados necessários.

I was curious, because by mistake I installed my win7 in PT-PT, and not PT-BR, thought the L # was reading this, and for this reason was in PT-PT for me, but then I saw that only has this Portuguese.

Silly doubt.

**Pull request merged**
