### PR TITLE
Button for Color Change

### PR DESCRIPTION
**Pull request by NeoSharp**

### CODE REVIEW

**Comment by h3h3** [comment]
change button to listbox and ill merge it

**Comment by NeoSharp** [comment]
Is this ok? If you want me to change the listbox size I can do it, or you can change the visual yourself. It looks small, and that is why I asked.

http://i.imgur.com/pzFwIoa.png

**Comment by lebocow** [comment]
That's look nice.I  think is okay

**Comment by NeoSharp** [comment]
I think h3h3 already added his own, and he used a combobox instead. I was wondering why he said listbox lol

**Pull request merged**
